/*
 * tanu_panel.c — LVGL panel client for Tanu AI assistant.
 *
 * Displays a character GIF, status bar, and response ticker directly to a
 * Linux framebuffer (/dev/fb0) via LVGL's fbdev driver. Connects to the
 * Tanu aiohttp WebSocket server to receive state updates and response tokens.
 *
 * Character GIF: /opt/tanu/assets/character.gif
 * Build: gcc -O2 -o tanu_panel tanu_panel.c -llvgl_linux -llvgl -lwebsockets -lm -lpthread
 * Usage: tanu_panel --ws-url ws://localhost:7337/ws/chat
 */

#include <getopt.h>
#include <libwebsockets.h>
#include <lvgl.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

/* Generated by LVGLImage.py --cf RAW --ofmt C --name gif_character */
LV_IMAGE_DECLARE(gif_character);

/* ---------------------------------------------------------------------------
 * Configuration
 * ------------------------------------------------------------------------- */

#define STATUS_BAR_H     18
#define RESPONSE_LINES   3
#define RESPONSE_BUF_SZ  4096
#define WS_RX_BUF_SZ     2048
#define ANIM_TICK_MS     50  /* 20 fps — GIF handles its own frame timing */

#define BG_COLOR         lv_color_hex(0x14141f)

/* ---------------------------------------------------------------------------
 * Globals
 * ------------------------------------------------------------------------- */

typedef enum {
    STATE_IDLE,
    STATE_LISTENING,
    STATE_THINKING,
    STATE_SPEAKING,
    STATE_ERROR,
} tanu_state_t;

static const char *state_names[] = {
    "idle", "listening", "thinking", "speaking", "error"
};

typedef struct {
    tanu_state_t state;
    int connected;
    char response[RESPONSE_BUF_SZ];
    char status[128];
    int dirty;
} panel_state_t;

static panel_state_t g_state = {
    .state     = STATE_IDLE,
    .connected = 0,
    .response  = "Waiting for server...",
    .status    = "Connecting...",
    .dirty     = 1,
};

/* LVGL widgets */
static lv_obj_t *scr;
static lv_obj_t *face_gif;
static lv_obj_t *status_label;
static lv_obj_t *response_label;

/* WebSocket context */
static struct lws_context *lws_ctx;
static struct lws *lws_wsi;
static char g_ws_url[256] = "ws://127.0.0.1:7337/ws/chat";

/* Signal handling */
static volatile int g_running = 1;

static void sighandler(int sig) {
    (void)sig;
    g_running = 0;
}

/* ---------------------------------------------------------------------------
 * State helpers
 * ------------------------------------------------------------------------- */

static tanu_state_t parse_state(const char *name) {
    for (int i = 0; i < (int)(sizeof(state_names) / sizeof(state_names[0])); i++) {
        if (strcmp(name, state_names[i]) == 0)
            return (tanu_state_t)i;
    }
    return STATE_IDLE;
}

/* Simple JSON value extractor for flat key:value pairs. */
static int json_get_string(const char *json, const char *key,
                           char *out, size_t out_sz) {
    char needle[128];
    snprintf(needle, sizeof(needle), "\"%s\"", key);
    const char *p = strstr(json, needle);
    if (!p) return -1;
    p = strchr(p + strlen(needle), ':');
    if (!p) return -1;
    p++;
    while (*p == ' ' || *p == '\t') p++;
    if (*p == '"') {
        p++;
        const char *end = strchr(p, '"');
        if (!end) return -1;
        size_t len = (size_t)(end - p);
        if (len >= out_sz) len = out_sz - 1;
        memcpy(out, p, len);
        out[len] = '\0';
        return 0;
    }
    const char *start = p;
    while (*p && *p != ',' && *p != '}' && *p != '\n') p++;
    size_t len = (size_t)(p - start);
    if (len >= out_sz) len = out_sz - 1;
    memcpy(out, start, len);
    out[len] = '\0';
    return 0;
}

/* ---------------------------------------------------------------------------
 * UI creation
 * ------------------------------------------------------------------------- */

static void create_ui(void) {
    printf("[UI] create_ui start\n"); fflush(stdout);

    scr = lv_screen_active();
    lv_obj_set_style_bg_color(scr, BG_COLOR, 0);
    lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, 0);
    printf("[UI] screen bg set\n"); fflush(stdout);

    int scr_w = 320; /* hardcoded for 320x240 ILI9341 */
    int pad = 4;

    /* Status bar — created first so it always renders */
    printf("[UI] creating status_label...\n"); fflush(stdout);
    status_label = lv_label_create(scr);
    lv_label_set_text(status_label, "Connecting...");
    lv_obj_set_style_text_color(status_label, lv_color_hex(0xaaaaaa), 0);
    lv_obj_set_style_text_font(status_label, &lv_font_montserrat_14, 0);
    lv_obj_align(status_label, LV_ALIGN_TOP_LEFT, pad, pad);
    printf("[UI] status_label OK\n"); fflush(stdout);

    /* Response ticker — created second so it always renders */
    printf("[UI] creating response_label...\n"); fflush(stdout);
    response_label = lv_label_create(scr);
    lv_label_set_text(response_label, "Tanu");
    lv_label_set_long_mode(response_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_width(response_label, scr_w - pad * 2);
    lv_obj_set_style_text_color(response_label, lv_color_hex(0xdddddd), 0);
    lv_obj_set_style_text_font(response_label, &lv_font_montserrat_14, 0);
    lv_obj_align(response_label, LV_ALIGN_BOTTOM_LEFT, pad, -pad);
    printf("[UI] response_label OK\n"); fflush(stdout);

    /* Character GIF — skip for now to test if labels render */
    printf("[UI] SKIPPING GIF for diagnosis\n"); fflush(stdout);
    printf("[UI] create_ui done\n"); fflush(stdout);
}

/* ---------------------------------------------------------------------------
 * UI update (called from timer)
 * ------------------------------------------------------------------------- */

static void update_ui(void) {
    lv_label_set_text(status_label, g_state.status);

    char display_resp[RESPONSE_BUF_SZ];
    snprintf(display_resp, sizeof(display_resp), "%s", g_state.response);
    lv_label_set_text(response_label, display_resp);
}

/* ---------------------------------------------------------------------------
 * WebSocket client (libwebsockets)
 * --------------------------------------------------------------------- */

typedef struct {
    unsigned char buf[WS_RX_BUF_SZ + LWS_PRE];
    size_t len;
    int ready;
} ws_user_data_t;

static int ws_callback(struct lws *wsi, enum lws_callback_reasons reason,
                       void *user, void *in, size_t len) {
    ws_user_data_t *ud = (ws_user_data_t *)user;

    switch (reason) {
    case LWS_CALLBACK_CLIENT_ESTABLISHED:
        g_state.connected = 1;
        snprintf(g_state.status, sizeof(g_state.status), "Connected");
        g_state.dirty = 1;
        break;

    case LWS_CALLBACK_CLIENT_RECEIVE: {
        if (ud->len + len > WS_RX_BUF_SZ) ud->len = 0;
        memcpy(ud->buf + LWS_PRE + ud->len, in, len);
        ud->len += len;
        if (lws_is_final_fragment(wsi)) {
            char *json = (char *)(ud->buf + LWS_PRE);
            json[ud->len] = '\0';

            char msg_type[64] = "";
            json_get_string(json, "type", msg_type, sizeof(msg_type));

            if (strcmp(msg_type, "token") == 0) {
                char content[512] = "";
                json_get_string(json, "content", content, sizeof(content));
                size_t curlen = strlen(g_state.response);
                if (curlen < RESPONSE_BUF_SZ - 2) {
                    if (g_state.state == STATE_IDLE ||
                        g_state.state == STATE_THINKING) {
                        g_state.response[0] = '\0';
                        curlen = 0;
                    }
                    strncat(g_state.response, content,
                            RESPONSE_BUF_SZ - curlen - 1);
                }
                g_state.state = STATE_SPEAKING;
                snprintf(g_state.status, sizeof(g_state.status), "Speaking...");
                g_state.dirty = 1;

            } else if (strcmp(msg_type, "response") == 0) {
                json_get_string(json, "content", g_state.response,
                                sizeof(g_state.response));
                g_state.dirty = 1;

            } else if (strcmp(msg_type, "done") == 0) {
                g_state.state = STATE_IDLE;
                snprintf(g_state.status, sizeof(g_state.status), "Ready");
                g_state.dirty = 1;

            } else if (strcmp(msg_type, "error") == 0) {
                char err_msg[256] = "Unknown error";
                json_get_string(json, "message", err_msg, sizeof(err_msg));
                snprintf(g_state.response, sizeof(g_state.response),
                         "Error: %s", err_msg);
                g_state.state = STATE_ERROR;
                snprintf(g_state.status, sizeof(g_state.status), "Error");
                g_state.dirty = 1;

            } else if (strcmp(msg_type, "tool_start") == 0) {
                char tool_name[128] = "";
                json_get_string(json, "name", tool_name, sizeof(tool_name));
                snprintf(g_state.status, sizeof(g_state.status),
                         "Using: %s...", tool_name);
                g_state.state = STATE_THINKING;
                g_state.dirty = 1;

            } else if (strcmp(msg_type, "tool_done") == 0) {
                snprintf(g_state.status, sizeof(g_state.status), "Thinking...");
                g_state.dirty = 1;

            } else if (strcmp(msg_type, "state") == 0) {
                char sname[32] = "";
                json_get_string(json, "state", sname, sizeof(sname));
                g_state.state = parse_state(sname);
                if (g_state.state == STATE_IDLE)
                    snprintf(g_state.status, sizeof(g_state.status), "Ready");
                else if (g_state.state == STATE_THINKING)
                    snprintf(g_state.status, sizeof(g_state.status), "Thinking...");
                else if (g_state.state == STATE_SPEAKING)
                    snprintf(g_state.status, sizeof(g_state.status), "Speaking...");
                g_state.dirty = 1;

            } else if (strcmp(msg_type, "status") == 0) {
                char provider[64] = "";
                char model[128] = "";
                json_get_string(json, "provider", provider, sizeof(provider));
                json_get_string(json, "model", model, sizeof(model));
                if (provider[0])
                    snprintf(g_state.status, sizeof(g_state.status),
                             "%s / %s", provider, model);
                g_state.dirty = 1;

            } else if (strcmp(msg_type, "_connected") == 0) {
                g_state.connected = 1;
                g_state.state = STATE_IDLE;
                snprintf(g_state.status, sizeof(g_state.status), "Ready");
                g_state.dirty = 1;

            } else if (strcmp(msg_type, "_disconnected") == 0) {
                g_state.connected = 0;
                g_state.state = STATE_ERROR;
                snprintf(g_state.status, sizeof(g_state.status),
                         "Disconnected");
                g_state.dirty = 1;
            }

            ud->len = 0;
        }
        break;
    }

    case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
        g_state.connected = 0;
        snprintf(g_state.status, sizeof(g_state.status), "Connection error");
        g_state.state = STATE_ERROR;
        g_state.dirty = 1;
        lws_wsi = NULL;
        break;

    case LWS_CALLBACK_CLIENT_CLOSED:
        g_state.connected = 0;
        snprintf(g_state.status, sizeof(g_state.status), "Closed");
        g_state.state = STATE_ERROR;
        g_state.dirty = 1;
        lws_wsi = NULL;
        break;

    default:
        break;
    }

    return 0;
}

static const struct lws_protocols ws_protocols[] = {
    {
        .name                  = "tanu-ws",
        .callback              = ws_callback,
        .per_session_data_size = sizeof(ws_user_data_t),
        .rx_buffer_size        = WS_RX_BUF_SZ,
    },
    { NULL, NULL, 0, 0 }
};

static void ws_connect(void) {
    if (lws_wsi) return;

    struct lws_client_connect_info info;
    memset(&info, 0, sizeof(info));

    const char *url = g_ws_url;
    const char *host = "127.0.0.1";
    int port = 7337;
    const char *path = "/ws/chat";

    if (strncmp(url, "ws://", 5) == 0) {
        url += 5;
    }
    char hostbuf[128];
    const char *slash = strchr(url, '/');
    if (slash) {
        size_t hlen = (size_t)(slash - url);
        if (hlen >= sizeof(hostbuf)) hlen = sizeof(hostbuf) - 1;
        memcpy(hostbuf, url, hlen);
        hostbuf[hlen] = '\0';
        host = hostbuf;
        path = slash;
        char *colon = strchr(hostbuf, ':');
        if (colon) {
            *colon = '\0';
            port = atoi(colon + 1);
        }
    }

    info.context   = lws_ctx;
    info.address   = host;
    info.port      = port;
    info.path      = path;
    info.host      = host;
    info.origin    = host;
    info.protocol  = ws_protocols[0].name;
    info.pwsi      = &lws_wsi;

    lws_client_connect_via_info(&info);
}

/* ---------------------------------------------------------------------------
 * Timer callback
 * ------------------------------------------------------------------------- */

static lv_timer_t *update_timer;

static void update_timer_cb(lv_timer_t *timer) {
    (void)timer;
    update_ui();
    lv_obj_invalidate(scr);
}

/* ---------------------------------------------------------------------------
 * Main
 * ------------------------------------------------------------------------- */

static void print_usage(const char *prog) {
    fprintf(stderr,
        "Usage: %s [OPTIONS]\n"
        "  --ws-url URL    WebSocket server URL (default: ws://127.0.0.1:7337/ws/chat)\n"
        "  --help          Show this help\n",
        prog);
}

int main(int argc, char **argv) {
    static struct option long_opts[] = {
        {"ws-url", required_argument, NULL, 'w'},
        {"help",   no_argument,       NULL, 'h'},
        {NULL,     0,                 NULL, 0},
    };
    int opt;
    while ((opt = getopt_long(argc, argv, "w:h", long_opts, NULL)) != -1) {
        switch (opt) {
        case 'w':
            strncpy(g_ws_url, optarg, sizeof(g_ws_url) - 1);
            break;
        case 'h':
            print_usage(argv[0]);
            return 0;
        default:
            print_usage(argv[0]);
            return 1;
        }
    }

    signal(SIGINT, sighandler);
    signal(SIGTERM, sighandler);

    /* Initialize LVGL */
    printf("[MAIN] lv_init...\n"); fflush(stdout);
    lv_init();

    /* Create fbdev display */
    printf("[MAIN] creating fbdev display...\n"); fflush(stdout);
    lv_display_t *disp = lv_linux_fbdev_create();
    if (!disp) {
        fprintf(stderr, "Failed to create LVGL fbdev display\n");
        return 1;
    }
    lv_linux_fbdev_set_file(disp, "/dev/fb0");
    printf("[MAIN] fbdev display ready\n"); fflush(stdout);

    /* Create UI */
    create_ui();

    /* Update timer — polls state and refreshes labels at 20 Hz */
    printf("[MAIN] creating timer...\n"); fflush(stdout);
    update_timer = lv_timer_create(update_timer_cb, ANIM_TICK_MS, NULL);
    printf("[MAIN] timer OK\n"); fflush(stdout);

    /* Initialize libwebsockets */
    struct lws_context_creation_info lws_info;
    memset(&lws_info, 0, sizeof(lws_info));
    lws_info.port = CONTEXT_PORT_NO_LISTEN;
    lws_info.protocols = ws_protocols;
    lws_info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT;

    lws_ctx = lws_create_context(&lws_info);
    if (!lws_ctx) {
        fprintf(stderr, "Failed to create libwebsockets context\n");
        return 1;
    }

    printf("Tanu LVGL panel starting...\n");
    printf("  WS URL: %s\n", g_ws_url);
    printf("  GIF:    embedded\n");
    printf("  Device: /dev/fb0\n");

    /* Initial label update */
    update_ui();
    lv_obj_invalidate(scr);

    /* Main event loop */
    unsigned long last_ws_attempt = 0;
    while (g_running) {
        unsigned long now_ms = (unsigned long)(time(NULL)) * 1000;

        if (!lws_wsi && (now_ms - last_ws_attempt > 3000)) {
            ws_connect();
            last_ws_attempt = now_ms;
        }

        lws_service(lws_ctx, 0);
        lv_timer_handler();

        usleep(1000);
    }

    printf("Tanu LVGL panel shutting down.\n");
    lws_context_destroy(lws_ctx);
    return 0;
}
